/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-11.10" *)
module counter(clk, rst, out);
  (* src = "counter.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "counter.v:4.18-4.21" *)
  output [3:0] out;
  wire [3:0] out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "counter.v:4.18-4.21" *)
  wire _13_;
  (* src = "counter.v:4.18-4.21" *)
  wire _14_;
  (* src = "counter.v:4.18-4.21" *)
  wire _15_;
  (* src = "counter.v:4.18-4.21" *)
  wire _16_;
  (* src = "counter.v:3.8-3.11" *)
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:9.8-9.15|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _18_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:9.8-9.15|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  INVX1 _24_ (
    .A(_16_),
    .Y(_06_)
  );
  INVX1 _25_ (
    .A(_17_),
    .Y(_07_)
  );
  NOR2X1 _26_ (
    .A(_13_),
    .B(_07_),
    .Y(_02_)
  );
  AND2X1 _27_ (
    .A(_13_),
    .B(_14_),
    .Y(_08_)
  );
  OAI21X1 _28_ (
    .A(_13_),
    .B(_14_),
    .C(_17_),
    .Y(_09_)
  );
  NOR2X1 _29_ (
    .A(_08_),
    .B(_09_),
    .Y(_03_)
  );
  NAND3X1 _30_ (
    .A(_13_),
    .B(_14_),
    .C(_15_),
    .Y(_10_)
  );
  OAI21X1 _31_ (
    .A(_15_),
    .B(_08_),
    .C(_17_),
    .Y(_11_)
  );
  AOI21X1 _32_ (
    .A(_15_),
    .B(_08_),
    .C(_11_),
    .Y(_04_)
  );
  OAI21X1 _33_ (
    .A(_06_),
    .B(_10_),
    .C(_17_),
    .Y(_12_)
  );
  AOI21X1 _34_ (
    .A(_06_),
    .B(_10_),
    .C(_12_),
    .Y(_05_)
  );
  (* src = "counter.v:5.1-10.4" *)
  DFFPOSX1 _35_ (
    .CLK(clk),
    .D(_20_),
    .Q(out[0])
  );
  (* src = "counter.v:5.1-10.4" *)
  DFFPOSX1 _36_ (
    .CLK(clk),
    .D(_21_),
    .Q(out[1])
  );
  (* src = "counter.v:5.1-10.4" *)
  DFFPOSX1 _37_ (
    .CLK(clk),
    .D(_22_),
    .Q(out[2])
  );
  (* src = "counter.v:5.1-10.4" *)
  DFFPOSX1 _38_ (
    .CLK(clk),
    .D(_23_),
    .Q(out[3])
  );
  assign _18_[3:1] = out[3:1];
  assign _19_[0] = _18_[0];
  assign _13_ = out[0];
  assign _14_ = out[1];
  assign _15_ = out[2];
  assign _16_ = out[3];
  assign _17_ = rst;
  assign _20_ = _02_;
  assign _21_ = _03_;
  assign _22_ = _04_;
  assign _23_ = _05_;
endmodule
