/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "halfadder.v:1.1-8.10" *)
module halfadder(a, b, sum, carry);
  (* src = "halfadder.v:2.8-2.9" *)
  input a;
  wire a;
  (* src = "halfadder.v:3.8-3.9" *)
  input b;
  wire b;
  (* src = "halfadder.v:4.9-4.12" *)
  output sum;
  wire sum;
  (* src = "halfadder.v:5.9-5.14" *)
  output carry;
  wire carry;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(carry)
  );
  XOR2X1 _1_ (
    .A(a),
    .B(b),
    .Y(sum)
  );
endmodule
