/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "and_gate.v:1.1-5.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:2.8-2.9" *)
  input a;
  wire a;
  (* src = "and_gate.v:2.10-2.11" *)
  input b;
  wire b;
  (* src = "and_gate.v:3.9-3.10" *)
  output y;
  wire y;
  assign y = a &(* src = "and_gate.v:4.10-4.13" *)  b;
endmodule
