/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "d_ff.v:1.1-12.10" *)
module d_ff(clk, rst, din, q);
  (* src = "d_ff.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "d_ff.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "d_ff.v:4.8-4.11" *)
  input din;
  wire din;
  (* src = "d_ff.v:5.13-5.14" *)
  output q;
  wire q;
  wire _0_;
  INVX1 _1_ (
    .A(rst),
    .Y(_0_)
  );
  (* src = "d_ff.v:6.1-11.4" *)
  DFFSR _2_ (
    .CLK(clk),
    .D(din),
    .Q(q),
    .R(_0_),
    .S(1'h1)
  );
endmodule
