/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "d_ff.v:1.1-12.10" *)
module d_ff(clk, rst, d, q);
  (* src = "d_ff.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "d_ff.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "d_ff.v:4.8-4.9" *)
  input d;
  wire d;
  (* src = "d_ff.v:5.13-5.14" *)
  output q;
  wire q;
  wire _0_;
  (* src = "d_ff.v:4.8-4.9" *)
  wire _1_;
  wire _2_;
  (* src = "d_ff.v:3.8-3.11" *)
  wire _3_;
  wire _4_;
  INVX1 _5_ (
    .A(_1_),
    .Y(_2_)
  );
  NOR2X1 _6_ (
    .A(_2_),
    .B(_3_),
    .Y(_0_)
  );
  (* src = "d_ff.v:6.1-11.4" *)
  DFFPOSX1 _7_ (
    .CLK(clk),
    .D(_4_),
    .Q(q)
  );
  assign _1_ = d;
  assign _3_ = rst;
  assign _4_ = _0_;
endmodule
