/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* src = "alu.v:1.1-14.10" *)
module alu(a, b, sel, result);
  (* src = "alu.v:2.17-2.18" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "alu.v:3.17-3.18" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "alu.v:4.11-4.14" *)
  input sel;
  wire sel;
  (* src = "alu.v:5.22-5.28" *)
  output [1:0] result;
  wire [1:0] result;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:579.28-579.29" *)
  wire [3:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [3:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:581.22-581.23" *)
  wire [1:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "1" *)
  wire [1:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [1:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [1:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "1" *)
  wire [1:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [1:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "1" *)
  wire [1:0] _08_;
  assign _00_[0] = ~_07_[0];
  assign _01_[2] = _00_[2] &(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:593.44-593.84" *)  _02_[1];
  assign _01_[3] = _00_[3] &(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:593.44-593.84" *)  _02_[1];
  assign _01_[0] = _00_[0] &(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:593.44-593.84" *)  sel;
  assign _01_[1] = _00_[1] &(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:593.44-593.84" *)  sel;
  assign _00_[3] = _04_[1] ^(* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _03_[0];
  assign _00_[1] = _07_[1] ^(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _06_[0];
  assign _03_[0] = a[0] &(* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.26-205.31" *)  b[0];
  assign _00_[2] = a[0] ^(* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.14-205.19" *)  b[0];
  assign _04_[1] = a[1] ^(* src = "alu.v:10.24-10.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.14-205.19" *)  b[1];
  assign _08_[0] = a[0] &(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.26-205.31" *)  _05_[0];
  assign _07_[0] = a[0] ^(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.14-205.19" *)  _05_[0];
  assign _07_[1] = a[1] ^(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:292.26-292.70|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:205.14-205.19" *)  _05_[1];
  assign _06_[0] = _08_[0] |(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:231.10-231.28" *)  _07_[0];
  assign result[1] = _01_[1] |(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:601.20-601.31" *)  _01_[3];
  assign result[0] = _01_[0] |(* src = "alu.v:10.30-10.30|alu.v:9.5-12.12|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:601.20-601.31" *)  _01_[2];
  assign _02_[1] = ~(* src = "alu.v:9.14-9.14|alu.v:9.5-12.12" *) sel;
  assign _05_[0] = ~(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:279.31-279.37" *) b[0];
  assign _05_[1] = ~(* src = "alu.v:11.24-11.29|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:279.31-279.37" *) b[1];
  assign _02_[0] = sel;
  assign _04_[0] = _00_[2];
endmodule

(* src = "counter.v:1.1-12.10" *)
module counter(clk, rst, count);
  (* src = "counter.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "counter.v:4.19-4.24" *)
  output [3:0] count;
  reg [3:0] count;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [31:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _02_;
  (* src = "counter.v:5.1-11.4" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _01_[0];
  (* src = "counter.v:5.1-11.4" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _02_[1];
  (* src = "counter.v:5.1-11.4" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _02_[2];
  (* src = "counter.v:5.1-11.4" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _02_[3];
  assign _01_[0] = ~count[0];
  assign _02_[1] = count[1] ^(* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[2];
  assign _00_[2] = count[2] &(* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[1];
  assign _00_[1] = count[1] &(* src = "counter.v:10.10-10.17|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _01_[31:1] = { 28'h0000000, count[3:1] };
  assign { _02_[31:4], _02_[0] } = { 27'h0000000, _00_[3], _01_[0] };
  assign { _00_[31:4], _00_[0] } = { 28'h0000000, count[0] };
endmodule

(* top =  1  *)
(* src = "mini_soc.v:1.1-30.10" *)
module mini_soc(clk, rst, alu_sel, mux_sel, soc_out);
  (* src = "mini_soc.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "mini_soc.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "mini_soc.v:4.11-4.18" *)
  input alu_sel;
  wire alu_sel;
  (* src = "mini_soc.v:5.11-5.18" *)
  input mux_sel;
  wire mux_sel;
  (* src = "mini_soc.v:6.18-6.25" *)
  output [1:0] soc_out;
  wire [1:0] soc_out;
  (* src = "mini_soc.v:9.12-9.19" *)
  wire [1:0] alu_out;
  (* src = "mini_soc.v:8.12-8.17" *)
  wire [3:0] count;
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:17.5-22.2" *)
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel(alu_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:11.9-15.2" *)
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:24.8-29.2" *)
  mux2x1 u_mux (
    .in0(count[3:2]),
    .in1(alu_out),
    .out(soc_out),
    .sel(mux_sel)
  );
endmodule

(* src = "mux2x1.v:1.1-9.10" *)
module mux2x1(in0, in1, sel, out);
  (* src = "mux2x1.v:2.17-2.20" *)
  input [1:0] in0;
  wire [1:0] in0;
  (* src = "mux2x1.v:3.17-3.20" *)
  input [1:0] in1;
  wire [1:0] in1;
  (* src = "mux2x1.v:4.11-4.14" *)
  input sel;
  wire sel;
  (* src = "mux2x1.v:5.18-5.21" *)
  output [1:0] out;
  wire [1:0] out;
  assign out[0] = sel ? (* src = "mux2x1.v:8.14-8.29" *) in1[0] : in0[0];
  assign out[1] = sel ? (* src = "mux2x1.v:8.14-8.29" *) in1[1] : in0[1];
endmodule
