/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "shift_reg.v:1.1-12.10" *)
module shift_reg(clk, rst, data_in, q);
  (* src = "shift_reg.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "shift_reg.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "shift_reg.v:4.14-4.21" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "shift_reg.v:5.17-5.18" *)
  output [7:0] q;
  wire [7:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  INVX1 _08_ (
    .A(rst),
    .Y(_02_)
  );
  INVX1 _09_ (
    .A(rst),
    .Y(_03_)
  );
  INVX1 _10_ (
    .A(rst),
    .Y(_04_)
  );
  INVX1 _11_ (
    .A(rst),
    .Y(_05_)
  );
  INVX1 _12_ (
    .A(rst),
    .Y(_06_)
  );
  INVX1 _13_ (
    .A(rst),
    .Y(_07_)
  );
  INVX1 _14_ (
    .A(rst),
    .Y(_00_)
  );
  INVX1 _15_ (
    .A(rst),
    .Y(_01_)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _16_ (
    .CLK(clk),
    .D(data_in[7]),
    .Q(q[0]),
    .R(_00_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _17_ (
    .CLK(clk),
    .D(q[0]),
    .Q(q[1]),
    .R(_07_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _18_ (
    .CLK(clk),
    .D(q[1]),
    .Q(q[2]),
    .R(_06_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _19_ (
    .CLK(clk),
    .D(q[2]),
    .Q(q[3]),
    .R(_05_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _20_ (
    .CLK(clk),
    .D(q[3]),
    .Q(q[4]),
    .R(_04_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _21_ (
    .CLK(clk),
    .D(q[4]),
    .Q(q[5]),
    .R(_03_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _22_ (
    .CLK(clk),
    .D(q[5]),
    .Q(q[6]),
    .R(_02_),
    .S(1'h1)
  );
  (* src = "shift_reg.v:6.1-11.4" *)
  DFFSR _23_ (
    .CLK(clk),
    .D(q[6]),
    .Q(q[7]),
    .R(_01_),
    .S(1'h1)
  );
endmodule
